# Service registers under this name
# Control the InternalResourceViewResolver:
spring:
  application:
    name: profiles-microservice-consumer-garcia-and-poveda
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
server:
  error:
    whitelabel:
      enabled: false

# Information for the Actuator endpoint
info:
  app:
    name: ProfileMicroserviceConsumer

profiles:
  service:
    url: http://profiles-microservice-producer-jorge-and-diego
